nmHoistingLimits: workspaces

nodeLinker: pnp

packageExtensions:
  connect-mongo@^4.4.1:
    peerDependencies:
      express-session: "*"
  eslint-config-react-app@^7.0.1:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  react-dev-utils@^12.0.1:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  react-scripts@5.0.1:
    peerDependencies:
      autoprefixer: "*"
      eslint-config-react-app: "*"
  ts-node-dev@^2.0.0:
    peerDependencies:
      "@types/node": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
